### PR TITLE
WIP: Restructured everything

### PR DESCRIPTION
**Pull request by herecydev**
Examples need porting over still, though that's trivial.
Fixed tests so that they run in "en-US". And are more friendly for those "over the pond".
Missing either a file, or something was renamed and hasn't been fixed.

### CODE REVIEW

**Comment by leosperry** [comment]
I'll need to look at this in depth later. (hopefully tonight) I'm open to the idea of restructuring the folders and had thought it would be needed at some point. I am not open to removing TheCollective. The classes in that project are not specific to Chroniton and could be used in much greater capacity. Therefore, they should not be bound to the Chroniton implementation.

**Comment by herecydev** [comment]
That's now updated with suggestions and included the samples back in.  At this point it's still broken but I'm pretty sure that was from your WIP branch.

**Comment by leosperry** [comment]
With the structure you propose, can it be compatible with traditional .NET builds? I'm sure netcore will take off, but at the moment, many shops are not ready to make the jump and Chroniton needs to support those shops.

**Comment by herecydev** [comment]
Yes of course, I've tried to target the lowest possible netstandard. I think I ended up with 1.1, which is consumable by:
- Net 4.5
- UWP
- Windows Phone 8/8.1
- Mono

**Comment by herecydev** [comment]
Anything else I can help with?

**Comment by leosperry** [comment]
Without a .nuspec file, I wanted to see it working with a traditional .NET console application. I've tried pulling in the Chroniton.NetCore nuget package into such an application without success. That's likely related to my limited netcore experience as I've only worked with it in my off hours, which due to family, upcoming holiday craziness at work, etc. has also been limited. If you could show a traditional .NET app and a .netcore  app running the same build, or at least point in the right direction, that would be tremendously helpful.

**Comment by herecydev** [comment]
Sure, the problem with the existing package is that it targets `netstandard1.6`, which translates to `net4.6.3`. You can see all the targets [here](https://github.com/dotnet/core-docs/blob/master/docs/core/tutorials/libraries.md). I've managed to reduce this down to `netstandard1.1` so that you can target this from a `net45` or above application.

If you want to demo what another `netstandard1.1` library would be like try using [microsoft's logging](https://www.nuget.org/packages/Microsoft.Extensions.Logging/). Just pull that via nuget into a net45 and everything should be fine.

Simple example:

``` c#
    class Program
    {
        static void Main(string[] args)
        {
            var factory = new Microsoft.Extensions.Logging.LoggerFactory();
            var logger = factory.CreateLogger("Program");

            logger.LogInformation("Hello World!");
        }
    }
```

**Comment by leosperry** [comment]
Thank you so much. I'm looking at this today.

**Comment by leosperry** [comment]
Overall, I'm liking the direction you're going with this. I'm having troubles with your branch though. I've pulled the latest and the tests do no line up with my WIP branch. In my branch all the tests pass. In your branch, the legacy tests do not build. Also, There are a lot of duplicate files in your branch. (leftovers from my work I'm sure)

**Comment by herecydev** [comment]
You're most welcome. I'm not entirely sure how this happened, but despite forking your serialize branch I managed to get an old copy of some of your files. That must have been my fault so I apologize. That's now updated and most things are now working fine for me. I've still got some issues with some of the CRON tests, I'm not sure if that's because of time differences (remember I'm in the UK and had some problems with parsing your date formats). But I think CRON is immune from that. Can you pull the latest commit and check if you get the same issues or not. Also if you see any outstanding files can you delete those from my branch (I'll accept that), as I'm not sure I can see which ones you're referring to.

**Pull request closed without merging**
